# This is a basic workflow to help you get started with Actions

name: Install Bannerlord
on:
    push:
      branches: [ CI ]


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the development branch

jobs:
  Install-Bannerlord:
    runs-on: windows-2019
    env:
      steamcmd_dir: C:\steamcmd\
      bannerlord_dir: C:\bannerlord\
    steps:
      - name: get steamcmd
        run: |
          md $Env:steamcmd_dir
          iwr "https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip" -o "${Env:steamcmd_dir}steamcmd.zip"
          Expand-Archive "${Env:steamcmd_dir}steamcmd.zip" $Env:steamcmd_dir

      # SteamCMD isn't reading scripts at the moment. Not sure why    
      #- name: write steamcmd file
      #  run: |
      #    "// update_bannerlord.txt
      #    //
      #    @ShutdownOnFailedCommand 1 //set to 0 if updating multiple servers at once
      #    @NoPromptForPassword 1
      #    login anonymous
      #    force_install_dir $Env:bannerlord_dir
      #    app_update 261550 validate      //bannerlord steam app id 261550
      #    quit" | out-file ${Env:steamcmd_dir}update_bannerlord.txt
      # yo github actions suck

      - name: install bannerlord
        env:
          steam_user: ${{ secrets.STEAM_USER }}
          steam_password: ${{ secrets.STEAM_PASSWORD }}
        run: start ".\steamcmd" -workingdirectory ${env:steamcmd_dir} -Args "+@ShutdownOnFailedCommand 1 +@NoPromptForPassword 1 +login ${env:steam_user} `"${env:steam_password}`" +force_install_dir ${env:bannerlord_dir} +app_update 261550 validate +quit" -wait
            
      - name: check bannerlord dir
        run: |
          ls ${Env:bannerlord_dir}steamapps\
          